sudo: required

dist: trusty

language: cpp

compiler:
    - gcc
    #- clang

addons:
    apt:
        packages:
            - libboost-all-dev
            - libcrypto++-dev

script: cd build && cmake ../ && make

notifications:
    email: false
    irc: "chat.freenode.net#kovri-dev"
    nick: kovri-ci
    password: 
